# Set up

Load needed packages, make sure they are installed.

```{r}
library(readr) 
library(dplyr) 
library(tidyverse) 
library(skimr) 
library(here)
library(tibble)
```

Load the data.

```{r}
#Path to data dictionary. Note the use of the here() package and not absolute paths
data_location <- here("Data","raw-data","TB_data_dictionary_2026-09-25.csv")
#load data dictionary
data_dictionary <- read_csv(data_location)

#Path to dataframes. 
data_location1 <- here("Data", "raw-data", "TB_burden_countries_2026-09-29.csv")
burden_data <- read_csv(data_location1)

data_location2 <- here("Data", "raw-data", "LTBI_estimates_2026-09-29.csv")
household_data <- read_csv(data_location2)

data_location3 <- here("Data", "raw-data", "TB_hiv_nonroutine_surveillance_2026-09-29.csv")
hiv_surveillance_data <- read_csv(data_location3)

data_location4 <- here("Data", "raw-data", "TB_contact_tpt_2026-09-29.csv")
contact_screening_data <- read_csv(data_location4)

data_location5 <- here("Data", "raw-data", "TB_policies_services_2026-09-29.csv")
policies_data <- read_csv(data_location5)

```

Use dictionary to make dataframes more readable

```{r}
##Full joining

join1 <- full_join(burden_data, contact_screening_data, by = c("country", "year"))

join2 <- full_join(hiv_surveillance_data, join1, by = c("country", "year"))

join3 <- full_join(household_data, join2, by = c("country", "year"))

full_join_data <- full_join(policies_data, join3, by = c("country", "year"))

#Only keeping the columns of interest 
full_data_small <- full_join_data %>% select("country", "year", "e_pop_num", "e_inc_num", "e_inc_tbhiv_num", "e_mort_exc_tbhiv_num", "e_mort_tbhiv_num", "e_mort_num", "cfr", "c_cdr", "tb_from_screen_available", "newinc_from_screen", "screen_data_available", "newinc_con", "newinc_con_screen", "newinc_con_tb", "prevtx_data_available.x", "e_hh_contacts", "hcw_tb_infected", "hcw_tot", "ident_pris", "newrel_prisoners", "plhiv_all_screen_data_available", "plhiv_all", "plhiv_all_screen", "prisoners_screen_data_available", "prisoners", "prisoners_screen", "miners_screen_data_available", "miners_screen", "miners", "district", "district_cxr", "district_wrd", "phcf", "phcf_wrd", "presumptive", "presumptive_wrd", "wrd_test_capacity", "m_wrd_error_rate_lte_5pct", "district_monitor_pos_rate", "m_wrd_tat_lt_48h")

#checking for empty rows, outside of the first two columns which will always be filled
empty_rows <- rowSums(is.na(full_data_small[, -c(1:2)]) | full_data_small[, -c(1:2)] == "") == ncol(full_data_small[, -c(1:2)])
any(empty_rows)    #all good

#checking for empty columns, outside of the first two columns which will always be filled
empty_cols <- colSums(is.na(full_data_small[, -c(1:2)]) | full_data_small[, -c(1:2)] == "") == nrow(full_data_small)
any(empty_cols)

full_data_small <- full_data_small %>% rename("Country" = "country", "Year" = "year", "Total Population" = "e_pop_num", "Incident TB Cases" = "e_inc_num", "Incident TB Among HIV Positive" = "e_inc_tbhiv_num", "TB Deaths (Excluding HIV)" = "e_mort_exc_tbhiv_num", "TB Deaths Among HIV Positive" = "e_mort_tbhiv_num", "All TB Deaths" = "e_mort_num", "Case Fatality Ratio" = "cfr", "Case Detection Rate" = "c_cdr", "Is Data on Cases Reported Through Screening Efforts Available?" = "tb_from_screen_available", "Number New/Relapse Cases Reported through Screening" = "newinc_from_screen", "Is Household Contact Data Available?" = "screen_data_available", "Number Household Contacts of Confirmed Cases" = "newinc_con", "Number Househould Contacts Screened" = "newinc_con_screen", "Number Household Contacts with New Case" = "newinc_con_tb", "Is Data Available on Number of Household Contacts Started on Preventative?" = "prevtx_data_available.x", "Household Contacts of TB Cases" = "e_hh_contacts", "Number of Healthcare Workers with TB" = "hcw_tb_infected", "Number of Healthcare Workers" = "hcw_tot", "Is Prisoner TB Data Available?" = "ident_pris", "Number New/Relapse Cases in Prisons" = "newrel_prisoners", "Is Data Available on Number of People with HIV Screened for TB?" = "plhiv_all_screen_data_available", "Number of People with HIV" = "plhiv_all", "Number of People with HIV Screened for TB" = "plhiv_all_screen", "Is Data Available on Number of Prisoners Screened for TB?" = "prisoners_screen_data_available", "Number of Prisoners" = "prisoners", "Number of Prisoners Screened for TB" = "prisoners_screen", "Is Data Available on Miners Exposed to Silica Dust Screened for TB?" = "miners_screen_data_available", "Number of Miners Screened for TB" = "miners_screen", "Number of Miners Exposed to Silica Dust" = "miners", "Total Number of Districts" = "district", "Number of Districts where Chest X-Ray Used for TB Screening" = "district_cxr", "Number of Districts with WHO Rapid Test Requirement" = "district_wrd", "Number of Primary Healthcare Facilities" = "phcf", "Number of PHCF with Access to WHO Rapid Test" = "phcf_wrd", "Number of People with Presumptive TB" = "presumptive", "Number of People with Presumptive TB Screened with WHO Rapid Test" = "presumptive_wrd", "Number of WHO Rapid Tests that can be Performed with Existing Equipment" = "wrd_test_capacity", "Number of Sites Providing WHO Rapid Test with Error Less Than 5%" = "m_wrd_error_rate_lte_5pct", "Number of Districts that Monitor Positivity Rate" = "district_monitor_pos_rate", "Number of Labs with 48hr Turnaround on 80% of Rapid Test Samples" = "m_wrd_tat_lt_48h")

```

Cleaning 
```{r}
##Major questions about screening at risk groups: Miners, Prisoners, Healthcare Workers, Househould Contacts, HIV

#Miners
df_miners <- full_data_small %>% filter(!is.na(`Is Data Available on Miners Exposed to Silica Dust Screened for TB?`)) %>% select("Country", "Year", "Total Population", "Incident TB Cases", "TB Deaths (Excluding HIV)", "All TB Deaths", "Case Fatality Ratio", "Case Detection Rate", "Is Data on Cases Reported Through Screening Efforts Available?", "Number New/Relapse Cases Reported through Screening", "Is Data Available on Miners Exposed to Silica Dust Screened for TB?", "Number of Miners Screened for TB", "Number of Miners Exposed to Silica Dust")

df_miners_yes <- df_miners %>% filter(`Is Data Available on Miners Exposed to Silica Dust Screened for TB?` == 1.00) 

#Prisoners
df_prisoners <- full_data_small %>% filter(!is.na(`Is Prisoner TB Data Available?`)) %>% select("Country", "Year", "Total Population", "Incident TB Cases", "TB Deaths (Excluding HIV)", "All TB Deaths", "Case Fatality Ratio", "Case Detection Rate", "Is Data on Cases Reported Through Screening Efforts Available?", "Number New/Relapse Cases Reported through Screening", "Is Prisoner TB Data Available?", "Number New/Relapse Cases in Prisons", "Is Data Available on Number of Prisoners Screened for TB?", "Number of Prisoners", "Number of Prisoners Screened for TB")

df_prisoners_yes <- df_prisoners %>% filter(`Is Prisoner TB Data Available?` == 1.00)

#Healthcare Workers
df_hcw <- full_data_small %>% filter(!is.na(`Number of Healthcare Workers`)) %>% select("Country", "Year", "Total Population", "Incident TB Cases", "TB Deaths (Excluding HIV)", "All TB Deaths", "Case Fatality Ratio", "Case Detection Rate", "Is Data on Cases Reported Through Screening Efforts Available?", "Number New/Relapse Cases Reported through Screening", "Number of Healthcare Workers with TB", "Number of Healthcare Workers")

#Household Contacts
df_hhc <- full_data_small %>% filter(!is.na(`Is Household Contact Data Available?`)) %>% select("Country", "Year", "Total Population", "Incident TB Cases", "TB Deaths (Excluding HIV)", "All TB Deaths", "Case Fatality Ratio", "Case Detection Rate", "Is Data on Cases Reported Through Screening Efforts Available?", "Number New/Relapse Cases Reported through Screening", "Is Household Contact Data Available?", "Number Household Contacts of Confirmed Cases", "Number Househould Contacts Screened", "Number Household Contacts with New Case", "Is Data Available on Number of Household Contacts Started on Preventative?", "Household Contacts of TB Cases")

df_hhc_yes <- df_hhc %>% filter(`Is Household Contact Data Available?` == 1.00 | `Is Household Contact Data Available?` == 60.00)

#HIV
df_hiv <- full_data_small %>% filter(!is.na(`Is Data Available on Number of People with HIV Screened for TB?`)) %>% select("Country", "Year", "Total Population", "Incident TB Cases", "TB Deaths (Excluding HIV)", "All TB Deaths", "Case Fatality Ratio", "Case Detection Rate", "Is Data on Cases Reported Through Screening Efforts Available?", "Number New/Relapse Cases Reported through Screening", "Incident TB Among HIV Positive", "TB Deaths Among HIV Positive", "Is Data Available on Number of People with HIV Screened for TB?", "Number of People with HIV", "Number of People with HIV Screened for TB")

df_hiv_yes <- df_hiv %>% filter(`Is Data Available on Number of People with HIV Screened for TB?` == 1.00)

##Major questions - Available technology

###df_tech <- full_join_small %>% I am commenting this out for now because I'm not sure if I need to include evaluation of the available technology in an area in the final project because I already have screening for at risk groups (hiv, hcw, miners, prisoner) and contact tracing and that already feels like a lot, will come back to this if necessary

```

Basic Exploration
```{r}
#Which countries are doing the screening
countries_miners_yes <- df_miners_yes %>% distinct(Country)
countries_prisoners_yes <- df_prisoners_yes %>% distinct(Country)
countries_hcw <- df_hcw %>% distinct(Country)
countries_hhc_yes <- df_hhc_yes %>% distinct(Country)
countries_hiv_yes <- df_hiv_yes %>% distinct(Country)
```